src/wp2hugo/internal/hugogenerator/hugopage/hugo_page.go
src/wp2hugo/internal/hugogenerator/testdata/testcase.WordPress.2024-07-01.xml
src/wp2hugo/internal/wpparser/wp_parser_setup.go

I've got a page on my site that has only an iframe. Before this commit, wp2hugo would crash when it reached that page but with this change it emits a warning and keeps going, which in my case allows it to finish processing the site.

Don't crash on empty pages

---

src/wp2hugo/internal/hugogenerator/hugopage/html_to_markdown_converter.go
src/wp2hugo/internal/hugogenerator/hugopage/html_to_markdown_converter_test.go

Sorry for including, found a bug where it breaks the gist parsing too, lets remove. 
@ashishb this removes the image processing change that was in 
- https://github.com/ashishb/wp2hugo/pull/39
as per 
https://github.com/ashishb/wp2hugo/pull/39#issuecomment-2330105043

Remove image param stripping

---

README.md
src/wp2hugo/internal/hugogenerator/hugo_gen_setup.go
src/wp2hugo/internal/hugogenerator/hugopage/hugo_page.go
src/wp2hugo/internal/hugogenerator/hugopage/hugo_page_test.go
src/wp2hugo/internal/wpparser/wp_parser_setup.go

Allow to apply conditional templates based on types, beyond the mere post/page dichotomy. 
WP `post_format` is written in pages frontmatter under the `type` field. Hugo will then apply the page template matching the `type` value, if any.
Notes:
- WP post_format: https://developer.wordpress.org/advanced-administration/wordpress/post-formats/
- Hugo type: https://gohugo.io/content-management/types/
- WP allows only a predefined set of normalized types. Hugo supports anything templated.

Translate WP post_format to Hugo type

---

README.md
src/wp2hugo/internal/hugogenerator/hugopage/hugo_page.go
src/wp2hugo/internal/hugogenerator/hugopage/wordpress_youtube_converter.go
src/wp2hugo/internal/hugogenerator/hugopage/wordpress_youtube_converter_test.go

YouTube videos URLs sitting alone on their own line are automatically turned into embeds by WP. We map them here to Hugo native `{{< youtube ID >}}` shortcode for similar feature.

Convert Youtube URLs to Hugo native shortcode

---

src/wp2hugo/internal/hugogenerator/custom_shortcodes.go
src/wp2hugo/internal/hugogenerator/hugopage/hugo_page.go
src/wp2hugo/internal/hugogenerator/hugopage/wordpress_audio_converter.go
src/wp2hugo/internal/hugogenerator/hugopage/wordpress_audio_converter_test.go

1. add our own basic custom Hugo shortcode, using HTML5 audio: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio
2. convert WP audio shortcode: https://wordpress.org/documentation/article/audio-shortcode/
3. add unit tests
Note: audio files added to WP media library and used in audio shortcode are not downloaded into the Hugo assets. I didn't investigate how to make that happen, it seems media are assumed to be image only but I didn't find where everything else gets filtered.

Support WP audio shortcode

---

src/wp2hugo/internal/hugogenerator/hugo_gen_setup.go
src/wp2hugo/internal/wpparser/wp_parser_setup.go

Avada (https://avada.com/) is a WP theme claiming close to 1 million clients. It achieved this by being a one-size-fits-all Swiss army knife, based on a page builder and dozens of shortcodes. As such, it has become unbearably bloated and slow over years. Meaning it's a natural candidate to decluttering and Hugo migraton.
Here I introduce generic support for 2 custom post types (portfolio and FAQ). I think it would be a good idea to let users apply the same code path to any arbitrary post type they want, defined as argument when calling wp2hugo from CLI

Handle Avada custom post types

---

src/wp2hugo/internal/hugogenerator/hugo_gen_setup.go
src/wp2hugo/internal/hugogenerator/hugopage/hugo_page.go
src/wp2hugo/internal/hugogenerator/hugopage/wordpress_audio_converter.go
src/wp2hugo/internal/hugogenerator/hugopage/wordpress_audio_converter_test.go

- support audio attachments added from Gutenberg audio block (directly using HTML)
- download target audio files locally into `/static` (partially address #50)
- optimize media URL finding regex
Reference: https://wordpress.com/support/wordpress-editor/blocks/audio-block/

Improve audio support

---

src/wp2hugo/internal/hugogenerator/hugo_gen_setup.go

This way, the `hugo` command can find the configuration file.

Locate the current shell into the new directory

---

src/wp2hugo/internal/wpparser/wp_parser_setup.go

Tags were being appended into categories.
This commit fixes that.
Ref: https://github.com/ashishb/wp2hugo/issues/76

fix: bug in tags being treated as categories

---

src/wp2hugo/internal/hugogenerator/hugo_gen_setup.go

Fixes #74
During media download, if the scheme is expressed as `//` replaces with the current URL's scheme before proceeding through the process.

Handle // scheme prefix

---

src/wp2hugo/internal/hugogenerator/hugopage/wordpress_youtube_converter.go

For quite a few years, I have been using [YouTube Lyte](https://wordpress.com/plugins/wp-youtube-lyte) for my YouTube embeds in WordPress, which uses plain text embeds, but adds two new "virtual URL schemes", namely `httpa`  for audio-only embeds and `httpv` for video embeds. This non-destructive change supports YouTube Lyte.

Support YouTube Lyte embeds

---

src/wp2hugo/go.mod
src/wp2hugo/go.sum
src/wp2hugo/internal/hugogenerator/hugopage/hugo_page.go

Handling of other media files like audio is still broken and not worth the fix right now.
From the attached GitHub issue
> Aeons ago I made [a blog post](https://habi.gna.ch/2003/07/26/canyoning/) including the image `https://habi.gna.ch/blog/images/Picture(2).jpg`
>
> When calling `wp2hugo` with
> ```bash
> ./src/wp2hugo/bin/wp2hugo -source habignach.WordPress.2024-10-29.xml  -download-media
> ```
> the process fails with
> ```bash
> 05:33:50PM DBG hugo_gen_setup.go:412 > Embedded media links links=1 page=https://habi.gna.ch/2003/07/26/canyoning/
> 05:33:50PM DBG hugo_gen_setup.go:416 > Downloading media files links=1
> 05:33:50PM INF media_cache_setup.go:33 > media https://habi.gna.ch/blog/images/Picture(2 will be fetched
> 05:33:50PM FTL main.go:43 > Error: error fetching media file …
```

fix: fix handling of image and PDF links with special characters

---

src/wp2hugo/internal/hugogenerator/hugo_gen_setup.go

This is a PR for issue https://github.com/ashishb/wp2hugo/issues/85.
Some commands did not work as intended on Windows, so I made some modifications to the code.
- `mkdir -p` can be replaced with `mkdir`, but it returns an error if the directory already exists.
- `rm -rf` can be replaced with `rmdir /S /Q`
- On Windows, `echo` outputs the " characters as-is.
To make the code OS-agnostic, I replaced the commands with `os.MkdirAll` and `os.RemoveAll`.

fix: resolve command incompatibility issue on Windows

---

src/wp2hugo/internal/hugogenerator/hugo_gen_setup.go

Images embedded in posts/pages may sometimes use downscaled image thumbnails or thumbnails sizes that don't exist anymore, patterned like `some-file-1920x1080.jpg`. We try to find the full-resolution image if any, like `some-file.jpg`, then fall-back to whatever URL was given in content if this failed.
This assumes Hugo image partials will handle resizing to theme width and responsive image sizes internally (see https://discourse.gohugo.io/t/hugo-image-processing-and-responsive-images/43110/4).

Image attachments: use full-resolution file if available

---

src/wp2hugo/cmd/hugomanager/cmd/suggest_description.go
src/wp2hugo/cmd/hugomanager/cmd/suggest_image_alt.go
src/wp2hugo/internal/hugomanager/imagealtsuggest/image_alt_suggest.go

feat: add `suggest-image-alt`

---

.github/workflows/release-hugomanager.yaml

Release failed with
```
⨯ release failed after 0s                  error=failed to parse tag 'hugomanager-0.1.1' as semver: Invalid Semantic Version
```
This fixes that

ci: fix release config

---

src/wp2hugo/internal/hugogenerator/generate_hugo_config.go
src/wp2hugo/internal/hugogenerator/hugo_gen_setup.go
src/wp2hugo/internal/mediacache/media_cache_setup.go
src/wp2hugo/internal/wpparser/wp_parser_setup.go
src/wp2hugo/internal/wpparser/wp_website_info.go

Earlier, the media path for a media /blog/2.png on a blog hosted on "example.com/blog" will be incorrect (example.com/blog/blog/2.png).
This commit fixes that.
Ref: https://github.com/ashishb/wp2hugo/issues/155

Hugo manager release

---

src/wp2hugo/internal/wpparser/wp_parser_setup.go

Sometimes, post titles can be arbitrarily long while the file names are limited to 255 characters.
So, for long post titles, convert them into short file names (up to 200 characters).
Ref: https://github.com/ashishb/wp2hugo/issues/158

fix: long post titles should not imply long file names

---

README.md
src/wp2hugo/internal/wpparser/wp_parser_setup.go

For reference : https://wpml.org/documentation/getting-started-guide/language-setup/language-url-options/#language-name-added-as-a-parameter
This slightly changes the Markdown files naming scheme, trying first to re-use the slug of the WordPress page (last member of the URL path). If no slug is found, this defaults to the current logic, using normalized title. Then, we try to extract the ?lang=XX or &lang=XX parameter if any.
The best case scenario is this :
- WP input : `https://website.com/some-page/` -> Hugo file `content/pages/some-page.md`,
- WP input `https://website.com/some-page/?lang=fr` -> Hugo file `content/pages/some-page.fr.md`
This automatically follows Hugo translating scheme. However, if the page slug was also translated through WPML, this doesn't work as-is anymore.

Support WPML translations using parameter URL scheme

---

src/wp2hugo/internal/hugogenerator/hugopage/wordpress_youtube_converter.go
src/wp2hugo/internal/hugogenerator/hugopage/wordpress_youtube_converter_test.go

Note: embeds with other video services still don't work…

Support Youtube with [embed] WP shortcode

---

src/wp2hugo/cmd/wp2hugo/main.go
src/wp2hugo/internal/hugogenerator/hugo_gen_setup.go
src/wp2hugo/internal/hugogenerator/hugo_generator_test.go
src/wp2hugo/internal/hugogenerator/hugopage/hugo_page.go
src/wp2hugo/internal/mediacache/media_cache_setup.go

1. add a `--download-all` CLI argument to enable downloading all media from WP library into `/static/`,
2. upon media downloading from origin server, gracefully handle servers requests rate thresholding (HTTP error 429: too many connections) with retries and timeouts, possibly using the returned HTTP header `Retry-After` if provided
3. finish the job started with 9e1fe1e550b041bbfcd2054a7fef9e7cb418b831: when downscaled WP image thumbnail links have been converted to original (full-res) size, ensure all thumbnails links in the post are converted to full-res too.

Images: improve handling

---

README.md
src/wp2hugo/cmd/wp2hugo/main.go
src/wp2hugo/internal/hugogenerator/hugo_gen_setup.go
src/wp2hugo/internal/hugogenerator/hugo_generator_test.go
src/wp2hugo/internal/wpparser/wp_parser_setup.go
src/wp2hugo/internal/wpparser/wp_website_info.go

Extend current Avada/WooCommerce support by allowing any arbitrary custom type.
This makes wp2hugo pretty much feature-complete from my perspective.
The native posts and pages code could possibly be refactored to use the (more generic) custom post type approach.

Allow users to specify custom post types as CSV argument when calling the binary

---

src/wp2hugo/cmd/hugomanager/cmd/move_content_with_attachments.go
src/wp2hugo/cmd/wp2hugo/main.go
src/wp2hugo/internal/gitutils/git_move.go
src/wp2hugo/internal/hugogenerator/hugo_gen_setup.go
src/wp2hugo/internal/hugomanager/contentmigratorv1/content_migrator_v1.go

Fix `context` related lint issues pointed out by golangci-lint upgrade from 2.1 -> 2.3

chore: fix lint issues
